name: CD 
on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      IMAGE: marcusjbaker/rcg:latest 
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v4
      - run: docker compose pull helloworld || true
      - run: docker compose up helloworld
