name: CD 
on:
  workflow_call:
    inputs:
      DOCKER_USERNAME:
        required: true
        type: string
      DOCKER_REGISTRY:
        required: true
        type: string
      DOCKER_IMAGE:
        required: true 
        type: string
    secrets:
      DOCKER_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - id: apt
        run: sudo apt-get update -y && sudo apt-get install -y openssh-client qemu-system podman xz-utils
      - run: podman machine init
      - run: podman machine start
      - id: login
        name: Podman login
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ inputs.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: ${{ inputs.DOCKER_REGISTRY }}

