name: CD 
on:
  workflow_call:
    inputs:
      image:
        default: marcusjbaker/rcg:latest
        required: false 
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    env:
      IMAGE: ${{ inputs.image }}
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker pull ${{ inputs.image }}
      - run: docker run -p 127.0.0.1:3000:8080/tcp ${{ inputs.image }} 

