name: CD 
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy:
    runs-on: self-hosted 
    environment: ${{ inputs.environment }}
    services:
      helloworld:
        image: marcusjbaker/rcg:latest
        ports:
          - 3000
        volumes:
          - data:/tmp/data
    steps:
      - run: while 1
