name: CD 
on:
  workflow_call:
jobs:
  deploy:
    services:
      helloworld:
        image: marcusjbaker/rcg:latest
        ports:
            - 3000:3000
    steps:
      - run: curl -o - http://helloworld:3000
