name: CD 
on:
  workflow_call:
    inputs:
      image:
        default: marcusjbaker/rcg:latest
        required: false 
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    services:
      web:
        image: ${{ inputs.image }}
        credentials:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      ports:
        - 300:8080
    steps:
      - run: sleep 60 

