name: CD 
on:
  workflow_call:
    inputs:
      DOCKER_IMAGE:
        required: true 
        type: string
      DOCKER_PORT:
        required: false 
        type: string
        default: 3000
      DOCKER_REGISTRY:
        required: true
        type: string
      DOCKER_USERNAME:
        required: true
        type: string
      HOST_PORT:
        required: false
        type: string
        default: 3000

    secrets:
      DOCKER_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: docker run -p 127.0.0.1:${{ inputs.HOST_PORT }}:${{ inputs.DOCKER_PORT }} ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_IMAGE }}

