name: CD 
on:
  workflow_call:
    inputs:
      DOCKER_USERNAME:
        required: true
        type: string
      DOCKER_REGISTRY:
        required: true
        type: string
      DOCKER_IMAGE:
        required: true 
        type: string
    secrets:
      DOCKER_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    services:
      web:
        image: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_IMAGE }}
        credentials:
          username: ${{ inputs.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        ports:
          - 3000:8080
    steps:
      - run: sleep 60 

