name: CD 
on:
  workflow_call:
jobs:
  deploy:
    #    runs-on: self-hosted
    services:
      helloworld:
        image: marcusjbaker/rcg:latest
        ports:
            - 3000
    steps:
      - run: while 1
