name: CI 
on:
  workflow_call:
    inputs:
      image:
        default: marcusjbaker/rcg:latest
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo REF_NAME=${{ github.ref_name }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v4
      - run: docker compose build helloworld
      - run: docker compose push helloworld
      - run: IMAGE="$( echo ${{ inputs.IMAGE }} | sed -Ee s/:latest/$GITHUB_SHA/ }} )" && docker tag ${{ inputs.IMAGE }} $IMAGE && docker push $IMAGE
