name: CI 
on:
  workflow_call:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: "${{ (github.ref_name == 'main') && 'production' || github.ref_name }}"
    env:
      IMAGE: marcusjbaker/rcg:latest 
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v4
      - run: docker compose build helloworld
      - run: docker compose push helloworld
      - run: IMAGE="$( echo ${{ env.IMAGE }} | sed -Ee s/:latest/$GITHUB_SHA/ }} )" && docker tag ${{ env.IMAGE }} $IMAGE && docker push $IMAGE
