name: ci 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      IMAGE: marcusjbaker/rcg:latest 
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password "${{ secrets.DOCKER_HUB_TOKEN }}"
      - run: docker compose build
      - run: docker compose push
