name: CI 
on:
  workflow_call:
    inputs:
      image:
        default: marcusjbaker/rcg:latest
        required: false 
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  image:
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ inputs.image }}
    steps:
      #- uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #    password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v4
      - id: build
        name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ inputs.image }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
      - id: push
        name: Push image to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push.outputs.registry-paths }}"
        #- run: docker compose build helloworld
        #- run: docker compose push helloworld
        #- run: IMAGE="$( echo ${{ inputs.IMAGE }} | sed -Ee s/:latest$/:$GITHUB_SHA/ )" && docker tag ${{ inputs.IMAGE }} $IMAGE && docker push $IMAGE
